# Generated by Django 4.0.4 on 2022-05-13 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kregle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Klub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.IntegerField(choices=[(1, 'Kręgle Club'), (2, 'Bilard Club'), (3, 'Dart Club')])),
            ],
        ),
        migrations.CreateModel(
            name='Rezerwacja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Tor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dostepnosc', models.IntegerField(choices=[(1, 'Dostępny'), (2, 'Brak')])),
                ('tor', models.IntegerField(choices=[(1, 'Krótki'), (2, 'Średni'), (3, 'Długi')])),
                ('osoby', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Zawodnik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=20)),
                ('nazwisko', models.CharField(max_length=20)),
                ('plec', models.CharField(choices=[('M', 'Mężczyzna'), ('K', 'Kobieta'), ('I', 'Coś innego')], max_length=1)),
                ('pseudonim', models.CharField(max_length=20)),
                ('nr_buta', models.IntegerField()),
                ('nr_telefonu', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Odpowiedz',
        ),
        migrations.AddField(
            model_name='rezerwacja',
            name='tor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kregle.tor'),
        ),
        migrations.AddField(
            model_name='klub',
            name='czlonkowie',
            field=models.ManyToManyField(to='kregle.zawodnik'),
        ),
    ]
