# Generated by Django 4.0.4 on 2022-05-31 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kregle', '0002_klub_rezerwacja_tor_zawodnik_delete_odpowiedz_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rezerwacja',
            name='data',
        ),
        migrations.RemoveField(
            model_name='tor',
            name='osoby',
        ),
        migrations.AddField(
            model_name='rezerwacja',
            name='dzien',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='rezerwacja',
            name='godziny',
            field=models.IntegerField(choices=[(1, '15:00'), (2, '16:00'), (3, '17:00'), (4, '18:00'), (5, '19:00'), (6, '20:00'), (7, '21:00'), (8, '22:00')], null=True),
        ),
        migrations.AddField(
            model_name='rezerwacja',
            name='osoby',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AddField(
            model_name='rezerwacja',
            name='rezerwujacy',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='klub',
            name='czlonkowie',
            field=models.ManyToManyField(blank=True, to='kregle.zawodnik'),
        ),
        migrations.AlterField(
            model_name='klub',
            name='nazwa',
            field=models.IntegerField(choices=[(1, 'Kręgle Club'), (2, 'Bilard Club'), (3, 'Dart Club'), (4, 'Brak')]),
        ),
        migrations.AlterField(
            model_name='rezerwacja',
            name='tor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kregle.tor'),
        ),
        migrations.AlterField(
            model_name='tor',
            name='dostepnosc',
            field=models.IntegerField(choices=[(1, 'Dostępny'), (2, 'Zajęty')]),
        ),
    ]
